export const ADD_CANDY = "ADD_CANDY";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const DELETE_CANDY = "DELETE_CANDY";
export const SET_CANDY_NAME = "SET_CANDY_NAME";
export const SET_LOADER = "SET_LOADER";
export const SET_CANDIES = "SET_CANDIES";
