export const ADD_CANDY = "ADD_CANDY";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const SET_CANDY_NAME = "SET_CANDY_NAME";
export const SET_LOADER = "SET_LOADER";
export const FETCH_CANDIES = "FETCH_CANDIES";
